config/routes.rb
Rails.application.routes.draw do

  
  root 'welcome#home'
  get  'about',   to: 'welcome#about'
  get  'contact', to: 'welcome#contact'
  
  
  resources :schools
  
  get 'signup',   to: 'users#new'
  resources :users, except: [:new]

end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name,        presence: true, length: { manimum: 6,  maximum: 40}
  validates :description, presence: true, length: { minimum: 0,  maximum: 150}
  validates :link,        presence: true, length: { minimum: 10, maximum: 100}
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,    presence: true, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
  validates :initials, presence: true
  validates :fname,    presence: true   
  validates :lname,    presence: true
  validates :sex,      presence: true
  validates :add1,     presence: true
  validates :city,     presence: true  
  validates :postcode, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:edit, :update, :show, :destroy ]
  def index
    @schools = School.all
  end  
  
  def new
    @school = School.new
  end
  
  def edit
  end
  
  def create
    @school = School.new(school_params)
    if @school.save
      flash[:success] = "Rijschool was successfully saved"
      redirect_to school_path(@school)
    else
      render 'new'
    end
  end
  
  def update
    if @school.update(school_params)
      flash[:success] = "Rijschool was successfully updated"
      redirect_to school_path(@school)
    else
      render 'edit'
    end    
  end
  
  def show
  end
  
  def destroy
     @school.destroy
     flash[:danger] = "Rijschool successfully deleted"
     redirect_to schools_path 
  end
  
  private
  def set_school
      @school = School.find(params[:id])
  end
  def school_params
    params.require(:school).permit(:name, :contact, :description, :link)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy ]
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Rijschool #{@user.username}"
      redirect_to schools_path 
    else
      render 'new'
    end 
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "User was successfully updated"
      redirect_to schools_path 
    else
      render 'edit'
    end    
  end
  
  def destroy
     @user.destroy
     flash[:danger] = "User successfully deleted"
     redirect_to users_path 
  end  
  
  private
  def set_user
      @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:username, :email, :password, :initials, :fname, :mname, :lname, :sex, :add1, :add2, :city, :postcode)
  end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end 
  
  def about
  end 
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="container" id="conFooter">
  <footer class="footer">
    <small>Copyright &copy; <a>Everest Rijschool Application</a>by <a href="">Raju Dey</a>
    </small>
    <nav>
      <ul>
        <li><small><%= link_to "Contact", contact_path %></small></li>
        <li><small><%= link_to "About", about_path %></small></li>
      </ul>
    </nav>
  </footer>
</div>

<!-- https://rijschool-everest.herokuapp.com/ -->

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}"%>'> 
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid" id="wholeNav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "Rijschool", root_path, class: "navbar-brand", id: "logo" %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">                                           
        <li><%= link_to "Rijschools", schools_path %></li>                  
        <li><a href="#">Link</a></li>                                       
        <li class="dropdown">                                               
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a> 
          <ul class="dropdown-menu">                                        
            <li><%= link_to "New Rijschools", new_school_path %></li>              
            <li><a href="#">Another action</a></li>                         
            <li><a href="#">Something else here</a></li>                    
            <li role="separator" class="divider"></li>                      
            <li><a href="#">Separated link</a></li>                       
            <li role="separator" class="divider"></li>                    
            <li><a href="#">One more separated link</a></li>                  
          </ul>                                                             
        </li>                                                               
      </ul>                                                               
      <form class="navbar-form navbar-left" role="search">                  
        <div class="form-group">                                            
          <input type="text" class="form-control" placeholder="Search">     
        </div>                                                            
        <button type="submit" class="btn btn-default">Submit</button>       
      </form>                                                               
      <ul class="nav navbar-nav navbar-right">                              
        <li><a href="#">Link</a></li>                                       
        <li class="dropdown">                                                
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Languages <span class="caret"></span></a> 
          <ul class="dropdown-menu">                                        
            <li><a href="#">English<img border="0" src="logo_w3s.gif" align="right"></a></li>  
            <li><a href="#">Nederlandse</a></li>                            
            <li><a href="#">Russian</a></li>                                
          </ul>                                                             
        </li>                                                               
      </ul>                                                                 
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rijschool</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/schools/_form.html.erb
<%= render 'shared/errors', obj: @school %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@school, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-sm-2 control-label"> 
          <%= f.label      :name %> 
        </div>
        <div class="col-sm-8"> 
          <%= f.text_field :name, class: "form-control", placeholder: "Name of Rijschool", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label"> 
          <%= f.label      :contact %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :contact, class: "form-control", placeholder: "Contact in Rijschool", autofocus: true %>
        </div>
      </div> 
      <div class="form-group">
        <div class="col-sm-2 control-label"> 
          <%= f.label      :description %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_area  :description, rows: 10, class: "form-control", placeholder: "Description about Rijschool", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label      :link %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :link, class: "form-control", placeholder: "Web link for Rijschool", autofocus: true %>
        </div>
      </div>  
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-6 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to Show Rijschools", schools_path %> ]
    </div>
  </div>
</div>

app/views/schools/edit.html.erb
<h1 align="center">Edit Rijschools Information</h1>

<%= render 'form' %>

app/views/schools/index.html.erb
<h1 align="center">Listing all Rijschools</h1>
  <% @schools.each do |f| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="school-title"> 
            <%= link_to f.name, school_path(f) %>
          </div>
          <div class="school-body"> 
            <p><%= truncate(f.description, length: 50) %></p>
            <p><%= f.contact %></p>
            <p><a href="#"><%= f.link %></a></p>
          </div>
          <div class="school-actions">
            <%= link_to "Delete Rijschool", school_path(f), method: :delete, data: {confirm: "Are you sure you want to delete?"}, class: "btn btn-xs btn-danger" %>
            <%= link_to "Edit Rijschool", edit_school_path(f), class: "btn btn-xs btn-primary" %>
          </div>     
        </div>
      </div>
    </div>
  <% end %>

app/views/schools/new.html.erb
<h1 align="center">Nieuwe Rijschool</h1>

<%= render 'form' %>

app/views/schools/show.html.erb
<h2 align="center">Rijshool : <%= @school.name %></h2>
<div class="well col-xs-8 col-xs-offset-2"> 
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@school.description) %>
  <p>Contact: <%= @school.contact %></p>
  <p>Website: <%= @school.link %></p>
  
  <div class="school-actions">
    <%= link_to "Show All Rijschools", schools_path, class: "btn btn-xs btn-success" %>  
    <%= link_to "Delete Rijschool", school_path(@school), method: :delete, data: {confirm: "Are you sure you want to delete?"}, class: "btn btn-xs btn-danger" %>
    <%= link_to "Edit Rijschool", edit_school_path(@school), class: "btn btn-xs btn-primary" %>
  </div> 
</div>  

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row"> 
    <div class="col-xs-8 col-xs-offset-2"> 
      <div class="panel panel-danger"> 
        <div class="panel-heading"> 
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %> prohibited this rijschool from being saved: 
          </h2>
          <div class="panel-body"> 
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-sm-2 control-label"> 
          <%= f.label      :username %> 
        </div>
        <div class="col-sm-8"> 
          <%= f.text_field :username, class: "form-control", placeholder: "User Name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label"> 
          <%= f.label      :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true %>
        </div>
      </div> 
      <div class="form-group">
        <div class="col-sm-2 control-label"> 
          <%= f.label      :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Password", autofocus: true %>
        </div>
      </div>       
      <div class="form-group">
        <div class="col-sm-2 control-label"> 
          <%= f.label      :initials %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field  :initials, class: "form-control", placeholder: "Initials", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label      :fname %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :fname, class: "form-control", placeholder: "First Name", autofocus: true %>
        </div>
      </div>  
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label      :mname %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :mname, class: "form-control", placeholder: "Middle Name", autofocus: true %>
        </div>
      </div>  
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label      :lname %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :lname, class: "form-control", placeholder: "Last Name", autofocus: true %>
        </div>
      </div>      
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label      :sex %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :sex, class: "form-control", placeholder: "Sex", autofocus: true %>
        </div>
      </div>   
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label      :add1 %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :add1, class: "form-control", placeholder: "Address 1", autofocus: true %>
        </div>
      </div> 
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label      :add2 %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :add2, class: "form-control", placeholder: "Address 2", autofocus: true %>
        </div>
      </div>    
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label      :city %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :city, class: "form-control", placeholder: "City", autofocus: true %>
        </div>
      </div>    
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label      :postcode %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :postcode, class: "form-control", placeholder: "Post Code", autofocus: true %>
        </div>
      </div>       
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ?  "Sign Up" : "Update account", class: "btn btn-primary btn-lg" ) %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-6 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to Show Users", schools_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1 align="center">Signup For Rijschool</h1>
<%= render 'form' %>

app/views/welcome/about.html.erb
<h1 align="center">About Page</h1>

app/views/welcome/contact.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 align="center">Contact Rijschool Instructor</h2>
    </div>
    <div class="panel-body">    
      <form role="form">
        <div class="form-group">      
<!--          <h1 class="contact">Any queries on Auto Lessons please contact :</h1> -->
<!--          <h1 class="contact">Evgeniya Rogozhina</h1>                           -->
<!--          <h1 class="contact">Contact : 0626397412</h1>                         --> 
<!--          <h1 class="contact">Email - rogozhina_evgeni@mail.ru</h1>             -->
          <label for="name">Name:</label>                                   
          <input type="text" class="form-control" id="name">                
        </div>                                                              
        <div class="form-group">                                              
          <label for="femail">From Email:</label>                           
          <input type="email" class="form-control" id="femail">                
        </div>                                                              
        <div class="form-group">                                            
          <label for="temail">To Email:</label>                              
          <input type="email" class="form-control" id="temail">             
        </div>                                                              
        <div class="form-group">                                            
          <label for="msg">Message:</label>                                  
          <textarea class="form-control" rows="5" id="msg"></textarea>       
        </div>                                                                
      <div class="checkbox">                                              
        <label><input type="checkbox"> Remember me</label>                
      </div>                                                              
        <button type="submit" class="btn btn-primary">Submit</button>       
      </form>
    </div>
  </div>
</div>

app/views/welcome/home.html.erb
<div class="center jumbotron">
<!-- <h1 class="contact">Web Site Under Construction</h1>                       -->
<!-- <h1 class="contact">Any queries on Auto Lessons please contact :</h1>      -->
<!-- <h1 class="contact">Evgeniya Rogozhina</h1>                                -->
<!-- <h1 class="contact">Contact : 0626397412</h1>                              -->
<!-- <h1 class="contact">Email - rogozhina_evgeni@mail.ru</h1>                  -->
  <%= link_to 'Sign up now', "#", class: "btn btn-primary btn-lg btn-xlarge" %> 
</div>